### ISSUE TITLE
run evaluate.py have a problem

### ISSUE THREAD

**Issue by Faker0715** [HKUST-KnowComp/DualMessagePassing#1]
Traceback (most recent call last):
  File "/home/faker/Desktop/code/DualMessagePassing-main/SubgraphCountingMatching/evaluate.py", line 439, in <module>
    eval_metric, eval_results = evaluate_epoch(
  File "/home/faker/Desktop/code/DualMessagePassing-main/SubgraphCountingMatching/evaluate.py", line 119, in evaluate_epoch
    pred_c, (pred_v, pred_e), ((p_v_mask, p_e_mask), (g_v_mask, g_e_mask)) = model(pattern, graph)
ValueError: too many values to unpack (expected 3)

**Comment by seanliu96** [comment]
Hi,

Thanks for creating an issue for evaluation. I fix this bug by removing the old functions. Please check the latest commit [275fab88447b991fcba0b457b9f3b275905816cc](https://github.com/HKUST-KnowComp/DualMessagePassing/commit/275fab88447b991fcba0b457b9f3b275905816cc).

**Comment by Faker0715** [comment]
thank you！

**Comment by seanliu96** [comment]
If this bug has been fixed, please help close this issue. Thank you!
